# Generated by Django 4.2.7 on 2023-11-08 16:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=255, verbose_name='Endereço Linha 1')),
                ('linha2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Linha 2')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado/Província/Região')),
                ('codigo_postal', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='O código postal não deve conter espaços', regex='^\\S+$')], verbose_name='Código Postal')),
                ('pais', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='TipoEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloCerveja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('ibu_min', models.PositiveIntegerField(blank=True, null=True)),
                ('ibu_max', models.PositiveIntegerField(blank=True, null=True)),
                ('srm_min', models.PositiveIntegerField(blank=True, null=True)),
                ('srm_max', models.PositiveIntegerField(blank=True, null=True)),
                ('abv_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('abv_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('perfil_sabor', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos', to='beerview.tipoestilo')),
            ],
        ),
        migrations.CreateModel(
            name='Cervejaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Cervejaria')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beerview.endereco', verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Cerveja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('abv', models.DecimalField(decimal_places=2, help_text='Alcohol By Volume', max_digits=4)),
                ('ibu', models.PositiveIntegerField(blank=True, help_text='International Bitterness Units', null=True, verbose_name='IBU')),
                ('srm', models.PositiveIntegerField(blank=True, help_text='Standard Reference Method - color', null=True, verbose_name='SRM')),
                ('descricao', models.TextField(blank=True)),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cervejas', to='beerview.cervejaria')),
                ('estilo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cervejas', to='beerview.estilocerveja')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('comentario', models.TextField()),
                ('cerveja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='beerview.cerveja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
