# Generated by Django 4.2.7 on 2023-11-08 18:52

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=255, verbose_name='endereço Linha 1')),
                ('linha2', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço Linha 2')),
                ('cidade', models.CharField(max_length=255)),
                ('regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='estado/Província/Região')),
                ('codigo_postal', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='O código postal não deve conter espaços', regex='^\\S+$')], verbose_name='Código Postal')),
                ('pais', django_countries.fields.CountryField(max_length=2, verbose_name='país')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
        migrations.CreateModel(
            name='EstiloCerveja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(choices=[('BO', 'Bock'), ('BA', 'Brown Ale'), ('DA', 'Dark Ale'), ('IP', 'Indian Pale Ale'), ('PA', 'Pale Ale'), ('PL', 'Pale Lager'), ('PO', 'Porter'), ('ES', 'Especial'), ('ST', 'Stout'), ('SA', 'Strong Ale'), ('WH', 'Wheat Beer'), ('WI', 'Wild Beer')], max_length=2)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('ibu_min', models.PositiveIntegerField(blank=True, help_text='Minimum International Bitterness Units', null=True)),
                ('ibu_max', models.PositiveIntegerField(blank=True, help_text='Maximum International Bitterness Units', null=True)),
                ('srm_min', models.PositiveIntegerField(blank=True, help_text='Minimum Standard Reference Method - color', null=True)),
                ('srm_max', models.PositiveIntegerField(blank=True, help_text='Maximum Standard Reference Method - color', null=True)),
                ('abv_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum Alcohol By Volume', max_digits=4, null=True)),
                ('abv_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Alcohol By Volume', max_digits=4, null=True)),
                ('perfil_sabor', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cervejaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beerview.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Cerveja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('abv', models.DecimalField(decimal_places=2, help_text='Alcohol By Volume', max_digits=4, verbose_name='ABV')),
                ('ibu', models.PositiveIntegerField(blank=True, help_text='International Bitterness Units', null=True, verbose_name='IBU')),
                ('srm', models.PositiveIntegerField(blank=True, help_text='Standard Reference Method - color', null=True, verbose_name='SRM')),
                ('descricao', models.TextField(blank=True)),
                ('cervejaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cervejas', to='beerview.cervejaria')),
                ('estilo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cervejas', to='beerview.estilocerveja')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('comentario', models.TextField()),
                ('cerveja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='beerview.cerveja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
            },
        ),
    ]
