# Generated by Django 4.2.7 on 2023-11-06 23:44

from django.db import migrations, models
import pesquisa_grupo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('IC', 'Iniciação Científica'), ('ME', 'Mestrando'), ('DO', 'Doutorando'), ('PD', 'Pós-Doutorando'), ('PR', 'Professor')], max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_integrantes/')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano_publicacao', models.PositiveIntegerField(validators=[pesquisa_grupo.models.max_value_current_year])),
                ('veiculo_publicacao', models.CharField(max_length=200)),
                ('autores', models.ManyToManyField(to='pesquisa_grupo.integrante')),
            ],
        ),
    ]
